version: '3'

services:

  # hr-user
  api-hr-user:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api-hr-user
    environment:
      SERVER_PORT: 9000
      POSTGRES_HOST: postgres_hr-user:5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SCHEMA: hr_user
    ports:
      - "9000:9000"
    depends_on:
      - postgres_hr-user

  # database
  postgres_hr-user:
    image: 'postgres:alpine'
    container_name: postgres_hr-user
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password